# Generated by Django 4.2 on 2024-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'product_name'), 'permissions': [('can_cancel_published', 'Сan cancel the publication of a product'), ('can_change_product_description', 'Сan change the product description'), ('can_change_product_category', 'Сan change the product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('ACTUAL', 'Актуальный'), ('DRAFT', 'Черновик'), ('CANCEL', 'Отменен')], default='ACTUAL', max_length=15, verbose_name='Статус публикации'),
        ),
    ]
