# Generated by Django 5.0.6 on 2024-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=5, verbose_name='Номер версии'),
        ),
    ]
